-- AlterTable
ALTER TABLE "Admin" ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "permissions" TEXT[] DEFAULT '{}',
ADD COLUMN "role" TEXT NOT NULL DEFAULT 'ADMIN',
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT NOW();
